services:
  hydrus_cv:
    build:
      context: ../../
      dockerfile: hydrus-software-stack/docker/cv/Dockerfile
    container_name: hydrus_cv_container
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./hydrus_cv:/hydrus_ws/src/hydrus_cv
    environment:
      - DISPLAY=$DISPLAY
    stdin_open: true  
    tty: true     